### ISSUE TITLE
instrucciones

### ISSUE THREAD

**Issue by mhamra** [ingadhoc/docker-odoo-adhoc#12]
En la documentaciòn READEME.md se indica

clone this repository "git clone git@github.com:ingadhoc/docker-odoo-adhoc.git"

Esto me da error de clave publica y no puedo clonar. Lo resolvì con 

git clone https://github.com/ingadhoc/docker-odoo-adhoc.git

Esta mal la documentación o me estoy perdiendo de algo?

**Comment by jjscarafia** [comment]
Marcelo, ese error te lo da porque no debes tener registradas las claves ssh con tu usuario, no es problema de permisos sobre el repo, igual agregué la opción para que quede). Gracias,
juan
