### ISSUE TITLE
jwilder/nginx-proxy

### ISSUE THREAD

**Issue by jujes** [ingadhoc/docker-odoo-adhoc#4]
1) ~~Hi, is possible deploy with **Spanish Spain** Extend and dependencies ?~~

2) I use nginx proxy, is poissible use **VIRTUAL_HOST** environment like this:

```
   environment:
      - VIRTUAL_HOST=www.sitedemo.dev
```

**Comment by jjscarafia** [comment]
Hi this images and docker-compose files are a beta project yet, we are using it a little for development and not for production (yet).
We haven't integrate nginx but we are looking forward to. So welcome for any suggestion or PR. 
Thanks!
Juan

**Comment by jjscarafia** [comment]
Now it is possible, done!
